[package]
name = "alchemist"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Robotechnic <@Robotechnic>"]
license = "MIT"
compiler = "0.11.0"
description = "A package to render skeletal notation in a human-readable format using cetz"
exclude = ["generate_images.sh", "generate_images.awk", ".gitignore","images"]